### ISSUE TITLE
TSS VI Missing

### ISSUE THREAD

**Issue by yao2389** [illuminated-g/tss#1]
hello,could please upload the tss project again,because I find that I can not open the classes,there are some vi are missing.thanks a lot!

**Comment by negentropicdev** [comment]
I'll have to take a look. This is still in development and wasn't finished yet so I don't expect everything to be working yet.

**Comment by yao2389** [comment]
Thanks for your great work,If you are finished,Please let us know,Beacuse this is a good tool for us.Thanks again!

**Comment by yao2389** [comment]
Thanks for your great work,If you are finished,Please let us know,Beacuse this is a good tool for us.Thanks again!
